### PR TITLE
Ported to NAN, compiles on 0.11.8.

### PR DESCRIPTION
**Pull request by kkoopa**
In response to #17 and #26, here is a patch that makes use of NAN.

### CODE REVIEW

**Comment by modeswitch** [comment]
This looks good. Does the `bridge.js`/`peer.html` test pass?

**Comment by kkoopa** [comment]
Unfortunately, I have no idea. Did the porting in a VM without X or many other things, so couldn't run Chrome, and I've never used webrtc, so I don't have any testing-code lying around. The module loaded and printed a couple lines when running tests/test.js. If someone with more insight and opportunity could do a test it would be great. I'll fix any problems that were introduced in the process, but usually things work if everything compiled successfully.

**Comment by modeswitch** [comment]
This isn't building on my machine:

```
make: Entering directory '/home/ack/work/node-webrtc/build'
  CXX(target) Release/obj.target/webrtc/src/binding.o
  CXX(target) Release/obj.target/webrtc/src/peerconnection.o
In file included from ../src/peerconnection.h:19:0,
                 from ../src/peerconnection.cc:16:
../src/peerconnection.cc: In static member function ‘static void PeerConnection::Run(uv_async_t*, int)’:
../node_modules/nan/nan.h:394:40: error: conversion from ‘v8::Persistent<v8::Object>’ to non-scalar type ‘v8::Local<v8::Object>’ requested
 # define NanObjectWrapHandle(obj) obj->handle_
                                        ^
../src/peerconnection.cc:146:31: note: in expansion of macro ‘NanObjectWrapHandle’
   v8::Local<v8::Object> lpc = NanObjectWrapHandle(self);
                               ^
webrtc.target.mk:147: recipe for target 'Release/obj.target/webrtc/src/peerconnection.o' failed
make: *** [Release/obj.target/webrtc/src/peerconnection.o] Error 1
make: Leaving directory '/home/ack/work/node-webrtc/build'
```

Maybe I'm missing something?

File: src/peerconnection.cc [hunk 1]
```diff
@@ -140,10 +140,10 @@ void PeerConnection::QueueEvent(AsyncEventType type, void* data)
 void PeerConnection::Run(uv_async_t* handle, int status)
 {
   TRACE_CALL;
-  HandleScope scope;
+  NanScope();
 
   PeerConnection* self = static_cast<PeerConnection*>(handle->data);
-  v8::Persistent<v8::Object> pc = self->handle_;
+  v8::Local<v8::Object> lpc = NanObjectWrapHandle(self);
```
Comment (modeswitch) [inline src/peerconnection.cc]: Why was this renamed?

Comment (kkoopa) [inline src/peerconnection.cc]: I thought the persistent handle would be needed as well as the local, but it was not referenced anywhere, so I removed it and neglected to rename back. I've fixed that now.

**Comment by kkoopa** [comment]
What version of Node are you using? Nevermind, it is 0.10.something. It seems that the problem is that the async data is a `Persistent<Object>` under 0.10, but a `Local<Object>` under 0.11.

0.10:
`v8::Local<v8::Object> pc = NanPersistentToLocal(NanObjectWrapHandle(self));`

0.11:
`v8::Local<v8::Object> pc = NanObjectWrapHandle(self);`

cc @rvagg: What's your take on this.

**Comment by modeswitch** [comment]
I'm using v0.10.21. I'll have a look this afternoon.

File: src/peerconnection.cc (hunk 1 above)
Comment (modeswitch) [inline src/peerconnection.cc]: Cool, if you push to your branch I'll merge to incoming.

Comment (modeswitch) [inline src/peerconnection.cc]: Also, I think this line should be `v8::Persistent<v8::Object> pc = NanObjectWrapHandle(self);`

File: src/datachannel.cc [hunk 2]
```diff
@@ -69,9 +68,9 @@ void DataChannel::QueueEvent(AsyncEventType type, void* data)
 void DataChannel::Run(uv_async_t* handle, int status)
 {
   TRACE_CALL;
-  HandleScope scope;
+  NanScope();
   DataChannel* self = static_cast<DataChannel*>(handle->data);
-  v8::Persistent<v8::Object> dc = self->handle_;
+  v8::Local<v8::Object> ldc = NanObjectWrapHandle(self);
```
Comment (modeswitch) [inline src/datachannel.cc]: Should be `v8::Persistent<v8::Object> dc = NanObjectWrapHandle(self);`.

**Comment by modeswitch** [comment]
Also, please add yourself to the AUTHORS file!

**Comment by modeswitch** [comment]
Tests run with those changes, so once you update your pull request I'll merge.

File: src/peerconnection.cc (hunk 1 above)
Comment (kkoopa) [inline src/peerconnection.cc]: It is these Persistent assignments that are problematic. You cannot assign to a persistent in new Node, so that will not work for 0.11.4+. The problem is that the wrapped object is persistent under 0.10 but not under 0.11, so the branches diverge. I have not seen this behavior before and am wondering why it manifests.

**Comment by kkoopa** [comment]
I think I've fixed it. Now it compiles on both 0.10 and 0.11. Have a go and see if it works for you too.
