### ISSUE TITLE
Build error 'module' object has no attribute 'check_input'

### ISSUE THREAD

**Issue by maritz** [node-webrtc/node-webrtc#104]
When tryin to build normall it fails. When running with --verbose I get this error message:

9> Downloading trunk/resources/audio_coding/F02.OUT30...
Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --bucket chromium-webrtc-resources trunk/resources' took 89.60 secs

________ running '/usr/bin/python trunk/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0' in '/home/dev/tools/node-webrtc/third_party/libwebrtc'
Error: Command /usr/bin/python trunk/webrtc/build/gyp_webrtc -Dextra_gyp_flag=0 returned non-zero exit status 1 in /home/dev/tools/node-webrtc/third_party/libwebrtc
Traceback (most recent call last):
  File "trunk/webrtc/build/gyp_webrtc", line 77, in <module>
    if not gyp_chromium.RunGN(gn_vars_dict):
  File "/home/dev/tools/node-webrtc/third_party/libwebrtc/trunk/build/gyp_chromium", line 319, in RunGN
    if subprocess.check_output(["getconf", "LONG_BIT"]).find("64") >= 0:
AttributeError: 'module' object has no attribute 'check_output'

gclient sync -D --verbose -j1 finished
For gclient sync -D --verbose -j1 something went wrong: error code 2, signal null.

**Comment by maritz** [comment]
Okay, the issue appears to be that I have Debian Squeeze which is still on Python 2.6. Any way around this?

Edit: I installed a 2.7 with pyenv. Now I'm running into the problem that debian 6 is on libstdc++6-4.4-dev which apparently does not include GLIBCXX_3.4.15 (only goes up to 3.4.13). Stuck there for now, might investigate further options later.

**Comment by modeswitch** [comment]
Squeeze is pretty old. If you're not planning to upgrade, maybe consider a VM like virtual box?

**Comment by maritz** [comment]
Sadly I'm stuck with it for now because my VPS provider can't tell me when an update to 7 will be available and don't really want to switch providers. :/

**Comment by modeswitch** [comment]
Closing as wontfix.
